### ISSUE TITLE
Tests failing on new clone?

### ISSUE THREAD

**Issue by claytonrcarter** [ryangjchandler/prettier-plugin-blade#37]
👋 Hi. Thanks for working on this! I tried this out and noticed a bunch of weird/unexpected formatting issues so I cloned it to see if I could contribute anything. But ... the tests aren't passing for me. This is a fresh install/clone w/ a successful `npm install`. I'm currently using node 14 w/ npm 6, but I also tried node 16 w/ npm 8 and got the same results. Any ideas on what I'm doing wrong?

```
~/src                                                                                           
❯ node --version
v14.19.0

~/src
❯ npm --version
6.14.16

~/src
❯ hub clone https://github.com/ryangjchandler/prettier-plugin-blade
Cloning into 'prettier-plugin-blade'...
remote: Enumerating objects: 907, done.
remote: Counting objects: 100% (907/907), done.
remote: Compressing objects: 100% (508/508), done.
remote: Total 907 (delta 428), reused 781 (delta 322), pack-reused 0
Receiving objects: 100% (907/907), 6.49 MiB | 10.85 MiB/s, done.
Resolving deltas: 100% (428/428), done.

~/src
❯ cd prettier-plugin-blade

~/src/prettier-plugin-blade main
❯ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tailwindcss@3.0.23 requires a peer of autoprefixer@^10.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @ryangjchandler/prettier-plugin-blade@ No repository field.
npm WARN @ryangjchandler/prettier-plugin-blade@ No license field.

added 412 packages from 353 contributors and audited 412 packages in 7.968s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


~/src/prettier-plugin-blade main                                                                                            
❯ npm run test

> @ryangjchandler/prettier-plugin-blade@ test /Users/crcarter/src/prettier-plugin-blade
> jest

 FAIL  tests/lexer.test.ts
  ● can generate directive tokens

    expect(received).toHaveProperty(path, value)

    Expected path: "raw"

    Expected value: "@if(auth()) @if(')' === '@test')"
    Received value: "@if(')"

      51 |
      52 |     expect(tokens[5]).toHaveProperty("type", TokenType.Directive);
    > 53 |     expect(tokens[5]).toHaveProperty("raw", "@if(auth()) @if(')' === '@test')");
         |                       ^
      54 |
      55 |     expect(tokens).toHaveLength(6);
      56 | });

      at Object.<anonymous> (tests/lexer.test.ts:53:23)

  ● can generate raw echo tokens when wrapped in parenthesis

    expect(received).toHaveProperty(path, value)

    Expected path: "type"

    Expected value: 2
    Received value: 1

       95 |     const raw = lex("{{!! 'yes' !!}}")[0];
       96 |
    >  97 |     expect(raw).toHaveProperty("type", TokenType.RawEcho);
          |                 ^
       98 |     expect(raw).toHaveProperty("raw", "{!! 'yes' !!}");
       99 | });
      100 |

      at Object.<anonymous> (tests/lexer.test.ts:97:17)

 FAIL  tests/fixtures.test.ts
  ● components/component-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 8
    + Received  + 4

    - @component('view')
    -     @slot('name', 'value')
    -     @slot('name2', true)
    -     @slot('name3')
    + @component('view') @slot('name', 'value') @slot('name2', true) @slot('name3')
    -         <div>Name3 Slot</div>
    + <div>Name3 Slot</div>
    -     @endslot
    + @endslot

    -     <div>Default Slot</div>
    + <div>Default Slot</div>
      @endcomponent
    -

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● components/component-namespace-tag.blade.php

    SyntaxError: Unexpected closing tag "x-slot". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (9:1)
       7 |     </x-slot:trigger><x-slot:footer>
       8 | <div>Footer Slot</div>
    >  9 | </x-slot>
         | ^^^^^^^^^
      10 | <div>
      11 |         Default Slot</div>
      12 |         </x-view>
       7 |     </x-slot:trigger><x-slot:footer>
       8 | <div>Footer Slot</div>
    >  9 | </x-slot>
         | ^^^^^^^^^
      10 | <div>
      11 |         Default Slot</div>
      12 |         </x-view>

      at y (node_modules/prettier/parser-html.js:40:2906)
      at Vl (node_modules/prettier/parser-html.js:111:2567)
      at Xl (node_modules/prettier/parser-html.js:111:4116)
      at Object.parse (node_modules/prettier/parser-html.js:111:4885)
      at Object.parse (node_modules/prettier-plugin-tailwindcss/dist/index.js:146:3296)
      at Object.parse$d [as parse] (node_modules/prettier/index.js:12975:19)
      at coreFormat (node_modules/prettier/index.js:14525:16)
      at formatWithCursor$1 (node_modules/prettier/index.js:14765:14)
      at node_modules/prettier/index.js:60959:12
      at format (node_modules/prettier/index.js:60979:12)

  ● components/component-tag.blade.php

    SyntaxError: Unexpected closing tag "x-slot". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (9:1)
       7 |     </x-slot:trigger><x-slot:footer>
       8 | <div>Footer Slot</div>
    >  9 | </x-slot>
         | ^^^^^^^^^
      10 | <div>
      11 |         Default Slot</div>
      12 |         </x-view>
       7 |     </x-slot:trigger><x-slot:footer>
       8 | <div>Footer Slot</div>
    >  9 | </x-slot>
         | ^^^^^^^^^
      10 | <div>
      11 |         Default Slot</div>
      12 |         </x-view>

      at y (node_modules/prettier/parser-html.js:40:2906)
      at Vl (node_modules/prettier/parser-html.js:111:2567)
      at Xl (node_modules/prettier/parser-html.js:111:4116)
      at Object.parse (node_modules/prettier/parser-html.js:111:4885)
      at Object.parse (node_modules/prettier-plugin-tailwindcss/dist/index.js:146:3296)
      at Object.parse$d [as parse] (node_modules/prettier/index.js:12975:19)
      at coreFormat (node_modules/prettier/index.js:14525:16)
      at formatWithCursor$1 (node_modules/prettier/index.js:14765:14)
      at node_modules/prettier/index.js:60959:12
      at format (node_modules/prettier/index.js:60979:12)

  ● directive/auth-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      @auth("admin")
    -     The user is authenticated...
    +  The user is authenticated...
      @endauth

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● directive/custom-if-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 12
    + Received  +  2

    - @disk('local')
    -     local!
    - @elsedisk('s3')
    -     s3!
    - @else
    -     not sure?
    - @enddisk
    + @disk('local') local! @elsedisk('s3') s3! @else not sure?@enddisk
    -
    - @unlessdisk('local')
    -     something not local
    - @enddisk
    + @unlessdisk('local')something not local@enddisk
    -

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● directive/error-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 6

      <label for="title">Post Title</label>

    - <input id="title" type="text" class="@error('title') is-invalid @enderror">
    + <input id="title" type="text" class="@error('title')
    +  is-invalid
    + @enderror" />

      @error('title')
    -     <div class="alert alert-danger">{{ $message }}</div>
    +
    + <div class="alert alert-danger">{{ $message }}</div>
    +
      @enderror

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● directive/if-else-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 6
    + Received  + 2

      @if(count($records) === 1)
    -     I have one record!
    - @elseif(count($records) > 1)
    +  I have one record! @elseif(count($records) > 1)I
    -     I have multiple records!
    - @else
    -     I don't have any records!
    + have multiple records! @else I don't have any records!
      @endif
    -

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● directive/prepend-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 3

      @prepend('scripts')
    -     <script src="/example.js"></script>
    +
    + <script src="/example.js"></script>
    +
      @endprepend

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● directive/push-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 3

      @push('scripts')
    -     <script src="/example.js"></script>
    +
    + <script src="/example.js"></script>
    +
      @endpush

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● directive/superfluous-spaces-directive.blade.php

    expect(received).toEqual(expected) // deep equality

    - Expected  - 9
    + Received  + 5

    - <h1>
    -     @if(true)
    + <h1>@if(true)
    -         goood
    +  goood
    -     @endif
    -
    -     @if("test" === "test")
    + @endif @if("test" === "test")
    -         baaad
    +  baaad
    -     @endif
    - </h1>
    + @endif</h1>
      ↵

      14 |         .map((part) => part.trimStart());
      15 |
    > 16 |     expect(format(original)).toEqual(expected);
         |                              ^
      17 | });
      18 |

      at tests/fixtures.test.ts:16:30

  ● php-tags/php-with-html-in-string.blade.php

    SyntaxError: Unexpected closing tag "title". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (2:40)
      1 | <?
    > 2 |     echo "<title>Some to be happy about</title>"
        |                                        ^^^^^^^^
      3 |     ?>
      4 | <h1>Awesome
      5 | </h1>
      1 | <?
    > 2 |     echo "<title>Some to be happy about</title>"
        |                                        ^^^^^^^^
      3 |     ?>
      4 | <h1>Awesome
      5 | </h1>

      at y (node_modules/prettier/parser-html.js:40:2906)
      at Vl (node_modules/prettier/parser-html.js:111:2567)
      at Xl (node_modules/prettier/parser-html.js:111:4116)
      at Object.parse (node_modules/prettier/parser-html.js:111:4885)
      at Object.parse (node_modules/prettier-plugin-tailwindcss/dist/index.js:146:3296)
      at Object.parse$d [as parse] (node_modules/prettier/index.js:12975:19)
      at coreFormat (node_modules/prettier/index.js:14525:16)
      at formatWithCursor$1 (node_modules/prettier/index.js:14765:14)
      at node_modules/prettier/index.js:60959:12
      at format (node_modules/prettier/index.js:60979:12)

Test Suites: 2 failed, 2 total
Tests:       13 failed, 29 passed, 42 total
Snapshots:   0 total
Time:        3.686 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ryangjchandler/prettier-plugin-blade@ test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ryangjchandler/prettier-plugin-blade@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/crcarter/.npm/_logs/2022-02-20T20_40_45_433Z-debug.log
```

**Comment by ryangjchandler** [comment]
Hey @claytonrcarter, thanks for checking out the plugin. We have a PR in the works that drastically changes the formatter, that includes a lot of fixes. 

The tests aren't passing because they're designed as fixtures for now so that we can ensure the formatting of the plugin is spot on.

**Comment by claytonrcarter** [comment]
Thanks @ryangjchandler. I'll keep an eye out for the improvements. Looking forward to them!

**Comment by claytonrcarter** [comment]
Hi again. Now that #30 is merged, I wanted to try this out again but I'm still seeing numerous test failures on a new clone and `npm install`. Is this a known issue of a still-in-development project, or are the tests passing for everyone else? 😄 

For me, it looks like all of the lexer tests are passing, but many (though not all) of the parser and fixture tests are still failing. 

Here's the output of just testing the parser: https://gist.github.com/claytonrcarter/1776662aa096da7eefa591af6bf17e99/raw/7fe59d797fa256842e2ee1d97c96cea47341cba9/jest-parser-failures.txt

And here's the output of just the fixture tests: https://gist.github.com/claytonrcarter/1776662aa096da7eefa591af6bf17e99/raw/7fe59d797fa256842e2ee1d97c96cea47341cba9/jest-fixture-failures.txt

Any guidance would be much appreciated. I'd love to be able to assist in the development of this!

**Comment by ryangjchandler** [comment]
There will definitely be lots of failing tests - as mentioned before, a lot of fixtures to ensure we cover certain things.

@olivernybroe Any ideas on why those CST/Parser tests are failing?

**Comment by claytonrcarter** [comment]
Ah, gotcha! If they're expected to fail at this point then 👍. Would it be helpful for me to tinker w/ trying to get some of them to pass, or would that just get in the way of other changes/plans in the works?

Also, I see a "Test" CI workflow that doesn't appear to be running. Is that intentional b/c the tests aren't currently passing? I could take a stab at setting that up to run for PRs and pushes to `main`, if desired.

Thanks again. Like I said, I'd love to be able to tinker a bit and help this along.

**Comment by olivernybroe** [comment]
Hey @claytonrcarter, thank you for wanting to help out! 

So all the parser tests were passing some weeks ago, however I have the same result here :) 

In regards to the CI workflow, we currently have it turned off because of github spam when having failing workflows ;) 

You are more than welcome to take a stab at it. Currently I have nothing uncommited, but might soon look into what changed in the parser since they are failing suddenly. 

Are there anything specific you would like to work on? Or is it just in general being able to contribute? :)

**Comment by olivernybroe** [comment]
I have fixed the parser tests 👍

**Comment by claytonrcarter** [comment]
Thank you both. I took some time to noodle around and came up w/ #39. I don't know those changes are great or desirable, but it helped me learn a bit. It's good to know that the test failures are semi-sorta-intended right now. That's what I was looking for. Thank you!

**Comment by ryangjchandler** [comment]
Awesome, thanks @claytonrcarter. I'm away this weekend but will take a look if I get a chance :)
