### ISSUE TITLE
Installation Instructions on README

### ISSUE THREAD

**Issue by iAmKevinMcKee** [ryangjchandler/prettier-plugin-blade#6]
I would love to start playing with this and potentially help contribute, but I'm not sure the best way to install this into my project. I found this: https://www.npmjs.com/package/prettier-plugin-blade but it's not your package and doesn't even exist anymore.

If you're waiting until the package is complete to add installation instructions, then no worries.

**Comment by ryangjchandler** [comment]
@iAmKevinMcKee Good thinking. I need to update the README anyway, will get on that soon. :)

**Comment by alexandersix** [comment]
@ryangjchandler Definite +1 for this. I have a few hours each week that I'd love to use to help get this project off the ground 👍🏻

**Comment by ryangjchandler** [comment]
@iAmKevinMcKee I've added some simple info to the README. Can only install from source/GitHub right now until it gets published on NPM (won't be until a pre-release/alpha is tagged).

**Comment by olivernybroe** [comment]
Thanks for the interest in this plugin 😄  If you find any bugs, please post an issue with it, so we can fix all the quirks!

**Comment by iAmKevinMcKee** [comment]
I ran `npm install https://github.com/ryangjchandler/prettier-plugin-blade` and `npm run dev` and now I get this error when I try to run prettier on any file:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@ryangjchandler/prettier-plugin-blade'
Require stack:
- /Users/kevinmckee/Code/portal/node_modules/prettier/index.js
- /Users/kevinmckee/Code/portal/node_modules/prettier/bin-prettier.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolve (node:internal/modules/cjs/helpers:100:19)
    at /Users/kevinmckee/Code/portal/node_modules/prettier/index.js:60907:20
    at Array.map (<anonymous>)
    at /Users/kevinmckee/Code/portal/node_modules/prettier/index.js:60905:43
    at Array.flatMap (<anonymous>)
    at Object.load (/Users/kevinmckee/Code/portal/node_modules/prettier/index.js:60895:56)
    at Object.load [as loadPlugins] (/Users/kevinmckee/Code/portal/node_modules/prettier/index.js:16258:23)
    at Object.getSupportInfo (/Users/kevinmckee/Code/portal/node_modules/prettier/index.js:60957:24)
    at getContextOptions (/Users/kevinmckee/Code/portal/node_modules/prettier/bin-prettier.js:19232:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kevinmckee/Code/portal/node_modules/prettier/index.js',
    '/Users/kevinmckee/Code/portal/node_modules/prettier/bin-prettier.js'
  ]
}
```

Is there anything else I need to do for installation?

**Comment by ryangjchandler** [comment]
Ah, this is because we haven't compiled any of the TypeScript yet...

Let me do it soon :)

**Comment by JayBizzle** [comment]
Hey,

Was looking at jumping in with this plugin a do some testing with it but for the life of me I cant get it to work. Have installed it via npm with the given instruction on in the README. I am using prettier extension for VS Code but it just says there is no formatter available for Blade files.

When i run from the command line, i get...

```
Error: Cannot find module '/xxxx/xxxx/xxxx/xxxx/node_modules/@ryangjchandler/prettier-plugin-blade/dist/src'. Please verify that the package.json has a valid "main" entry
````

Any help appreciated.

Thanks

**Comment by ryangjchandler** [comment]
@JayBizzle Ah, I think we need to actually point it to the `plugin.js` file. Will test this later on and comment back here.

**Comment by mikefrancis** [comment]
@ryangjchandler I think you're right, if you follow the current installation instructions and navigate to `./node_modules/@ryangjchandler/prettier-plugin-blade/package.json` and make sure `main` is set to:

```json
{
  // ...
  "main": "dist/src/plugin.js",
  // ...
}
```

Then it works, for example:

```bash
$ npx prettier --list-different resources/views
resources/views/welcome.blade.php
```

**Comment by ryangjchandler** [comment]
@mikefrancis Merged. Thanks!

**Comment by JayBizzle** [comment]
Can confirm i can now run this from the command line (thanks @mikefrancis), but the VS Code Prettier extension still thinks there is no formatter available for Blade files 😕

**Comment by JayBizzle** [comment]
> Can confirm i can now run this from the command line (thanks @mikefrancis), but the VS Code Prettier extension still thinks there is no formatter available for Blade files 😕

My bad, a restart of VSCode sorted it
